### ISSUE TITLE
aptでインストールできるようにするためのハードルが高い

### ISSUE THREAD

**Issue by narugit** [naruhiyo/aman#30]
### todo
- [x] Launchpadへのユーザー登録
- [x] GPG鍵の作成
- [x] 鍵公開サーバーへGPG鍵アップロード
- [x] LaunchpadでGPG鍵をimportして、署名する
- [x] CoC署名を行う
- [x] debパッケージのためのUbuntu環境の構築 (Docker)
- [ ] どんな言語でもいいのでhello world表示するだけのスクリプトをLaunchpadで公開する
- [ ] hello worldスクリプトをapt installでインストール可能か試す
- [ ] golangでhello world表示するだけのスクリプトをLaunchpadで公開する
- [ ] amanをLaunchpadで公開する

**Comment by hiyoko3** [comment]
今回は apt を利用しないため本issue をクローズします。
