### ISSUE TITLE
カンマ区切りのオプションを選択するとカンマが入ってしまう

### ISSUE THREAD

**Issue by narugit** [naruhiyo/aman#66]
![image](https://user-images.githubusercontent.com/28133383/103395288-e9734c80-4b70-11eb-87c4-3b3005429bb4.png)

**Comment by hiyoko3** [comment]
カンマを除去するだけで進行

他の記号は issue が挙げられてから対応

**Comment by narugit** [comment]
`master`にマージする必要あり
